use_frameworks!

platform :ios, '13.0'

target 'YueYuNetwork_Example' do
  pod 'YueYuNetwork', :path => '../'

  target 'YueYuNetwork_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # 设置所有 Pod的最低部署版本为 iOS 12.0
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
